import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

import { Toaster } from "react-hot-toast";
import "react-toastify/dist/ReactToastify.css";
import "react-datepicker/dist/react-datepicker.css";
import Navbar from "@/components/Navbar/Navbar";
import { carryFont } from "@/utils/font";
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata: Metadata = {
  title: "Carry Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${carryFont.className} bg-[#fbfbfb]`}>
        {/* <NextTopLoader
          color="#31302E"
          height={3}
          crawl={false}
          showSpinner={false}
          zIndex={1600}
          showAtBottom={false}
        />
        <RootLayout>
        <main>{children}</main>
        </RootLayout> */}
        <Toaster position="top-right" />
        <main>
        {children}
        </main>

        
      </body>
    </html>
  );
}
